name: flutter_boilerplate
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^0.5.3+4
  http: ^0.12.0+2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
    
  linter: ^0.1.96
  pedantic: ^1.0.0

flutter:

  uses-material-design: true